//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST_WS_CMD.NS_WS_GUITARE_LOCAl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NS_WS_GUITARE_LOCAl.WS_GUITARESoap")]
    public interface WS_GUITARESoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Get_DateResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Date", ReplyAction="*")]
        TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponse Get_Date(TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Date", ReplyAction="*")]
        System.Threading.Tasks.Task<TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponse> Get_DateAsync(TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_DateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Date", Namespace="http://tempuri.org/", Order=0)]
        public TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequestBody Body;
        
        public Get_DateRequest() {
        }
        
        public Get_DateRequest(TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_DateRequestBody {
        
        public Get_DateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_DateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_DateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponseBody Body;
        
        public Get_DateResponse() {
        }
        
        public Get_DateResponse(TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_DateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_DateResult;
        
        public Get_DateResponseBody() {
        }
        
        public Get_DateResponseBody(string Get_DateResult) {
            this.Get_DateResult = Get_DateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_GUITARESoapChannel : TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GUITARESoapClient : System.ServiceModel.ClientBase<TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap>, TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap {
        
        public WS_GUITARESoapClient() {
        }
        
        public WS_GUITARESoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_GUITARESoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARESoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponse TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap.Get_Date(TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest request) {
            return base.Channel.Get_Date(request);
        }
        
        public string Get_Date() {
            TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest inValue = new TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest();
            inValue.Body = new TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequestBody();
            TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponse retVal = ((TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap)(this)).Get_Date(inValue);
            return retVal.Body.Get_DateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponse> TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap.Get_DateAsync(TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest request) {
            return base.Channel.Get_DateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateResponse> Get_DateAsync() {
            TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest inValue = new TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequest();
            inValue.Body = new TEST_WS_CMD.NS_WS_GUITARE_LOCAl.Get_DateRequestBody();
            return ((TEST_WS_CMD.NS_WS_GUITARE_LOCAl.WS_GUITARESoap)(this)).Get_DateAsync(inValue);
        }
    }
}
