//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoisCorp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoisCorp()
        {
            this.Guitares = new HashSet<Guitare>();
        }
    
        public int idBoisCorps { get; set; }
        public string nomBoisCorps { get; set; }
        public int idMatériel_ { get; set; }
    
        public virtual Materiel Materiel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guitare> Guitares { get; set; }
    }
}
