//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class choixMicro
    {
        public int idMicro1 { get; set; }
        public int nombreMicro { get; set; }
        public int idMicro3 { get; set; }
        public int idMicro2 { get; set; }
        public int idGuitare { get; set; }
    
        public virtual Guitare Guitare { get; set; }
        public virtual microPosition1 microPosition1 { get; set; }
        public virtual microPosition3 microPosition3 { get; set; }
        public virtual microPosition2 microPosition2 { get; set; }
    }
}
