//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guitare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guitare()
        {
            this.choixMicroes = new HashSet<choixMicro>();
        }
    
        public int idGuitare { get; set; }
        public string tempsPreparation { get; set; }
        public Nullable<int> prix { get; set; }
        public int idVibrato { get; set; }
        public int idBoisTouche { get; set; }
        public int idBoisCorps { get; set; }
        public int idBoisManche { get; set; }
        public int idClient { get; set; }
    
        public virtual BoisCorp BoisCorp { get; set; }
        public virtual BoisManche BoisManche { get; set; }
        public virtual BoisTouche BoisTouche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<choixMicro> choixMicroes { get; set; }
        public virtual Client Client { get; set; }
        public virtual typeVibrato typeVibrato { get; set; }
    }
}
