//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class microPosition1
    {
        public int idMicro1 { get; set; }
        public string nomMicroBas { get; set; }
        public int idMatériel_ { get; set; }
    
        public virtual choixMicro choixMicro { get; set; }
        public virtual Materiel Materiel { get; set; }
    }
}
