//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C_BASE_AZUR : DbContext
    {
        public C_BASE_AZUR()
            : base("name=C_BASE_AZUR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoisCorp> BoisCorps { get; set; }
        public virtual DbSet<BoisManche> BoisManches { get; set; }
        public virtual DbSet<BoisTouche> BoisTouches { get; set; }
        public virtual DbSet<choixMicro> choixMicroes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Guitare> Guitares { get; set; }
        public virtual DbSet<Materiel> Materiels { get; set; }
        public virtual DbSet<microPosition1> microPosition1 { get; set; }
        public virtual DbSet<microPosition2> microPosition2 { get; set; }
        public virtual DbSet<microPosition3> microPosition3 { get; set; }
        public virtual DbSet<typeVibrato> typeVibratoes { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<ipv6_database_firewall_rules> ipv6_database_firewall_rules { get; set; }
    }
}
